<a href="https://colab.research.google.com/github/idreesibrahim9/Medical-Dataset/blob/main/pandas_medicaldataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('content_drive')

Mounted at content_drive

In [3]:
df=pd.read_csv("content_drive/MyDrive/medical_insurance.csv")

In [4]:
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
2767   47  female  45.320         1     no  southeast   8569.86180
2768   21  female  34.600         0     no  southwest   2020.17700
2769   19    male  26.030         1    yes  northwest  16450.89470
2770   23    male  18.715         0     no  northwest  21595.38229
2771   54    male  31.600         0     no  southwest   9850.43200

[2772 rows x 7 columns]

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
coder=LabelEncoder()

In [7]:
df["sex"] = df["sex"].astype(str)
df["sex"] = coder.fit_transform(df["sex"])

In [8]:
df["smoker"] = df["smoker"].astype(str)
df["smoker"] = coder.fit_transform(df["smoker"])

In [9]:
df["region"] = df["region"].astype(str)
df["region"] = coder.fit_transform(df["region"])

In [10]:
x=(df.drop("charges",axis=1))
y=df["charges"]

In [11]:
x

      age  sex     bmi  children  smoker  region
0      19    0  27.900         0       1       3
1      18    1  33.770         1       0       2
2      28    1  33.000         3       0       2
3      33    1  22.705         0       0       1
4      32    1  28.880         0       0       1
...   ...  ...     ...       ...     ...     ...
2767   47    0  45.320         1       0       2
2768   21    0  34.600         0       0       3
2769   19    1  26.030         1       1       1
2770   23    1  18.715         0       0       1
2771   54    1  31.600         0       0       3

[2772 rows x 6 columns]

In [12]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
2767     8569.86180
2768     2020.17700
2769    16450.89470
2770    21595.38229
2771     9850.43200
Name: charges, Length: 2772, dtype: float64